# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/sara/Dropbox/Reaching Study/GitRepo/ReachPredictor/upredictor/uPredictor"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/sara/Dropbox/Reaching Study/GitRepo/ReachPredictor/upredictor/uPredictor"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sara/Dropbox/Reaching Study/GitRepo/ReachPredictor/upredictor/uPredictor/CMakeFiles" "/home/sara/Dropbox/Reaching Study/GitRepo/ReachPredictor/upredictor/uPredictor/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sara/Dropbox/Reaching Study/GitRepo/ReachPredictor/upredictor/uPredictor/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uPredictor

# Build rule for target.
uPredictor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uPredictor
.PHONY : uPredictor

# fast build rule for target.
uPredictor/fast:
	$(MAKE) -f CMakeFiles/uPredictor.dir/build.make CMakeFiles/uPredictor.dir/build
.PHONY : uPredictor/fast

#=============================================================================
# Target rules for targets named ubccamera

# Build rule for target.
ubccamera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubccamera
.PHONY : ubccamera

# fast build rule for target.
ubccamera/fast:
	$(MAKE) -f UBCCamera/CMakeFiles/ubccamera.dir/build.make UBCCamera/CMakeFiles/ubccamera.dir/build
.PHONY : ubccamera/fast

#=============================================================================
# Target rules for targets named alglib

# Build rule for target.
alglib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alglib
.PHONY : alglib

# fast build rule for target.
alglib/fast:
	$(MAKE) -f ALGLIB/CMakeFiles/alglib.dir/build.make ALGLIB/CMakeFiles/alglib.dir/build
.PHONY : alglib/fast

#=============================================================================
# Target rules for targets named ubckinect

# Build rule for target.
ubckinect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubckinect
.PHONY : ubckinect

# fast build rule for target.
ubckinect/fast:
	$(MAKE) -f UBCKinect/CMakeFiles/ubckinect.dir/build.make UBCKinect/CMakeFiles/ubckinect.dir/build
.PHONY : ubckinect/fast

#=============================================================================
# Target rules for targets named ubckinectgui

# Build rule for target.
ubckinectgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubckinectgui
.PHONY : ubckinectgui

# fast build rule for target.
ubckinectgui/fast:
	$(MAKE) -f UBCKinectGUI/CMakeFiles/ubckinectgui.dir/build.make UBCKinectGUI/CMakeFiles/ubckinectgui.dir/build
.PHONY : ubckinectgui/fast

#=============================================================================
# Target rules for targets named ubcgui

# Build rule for target.
ubcgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubcgui
.PHONY : ubcgui

# fast build rule for target.
ubcgui/fast:
	$(MAKE) -f UBCGUI/CMakeFiles/ubcgui.dir/build.make UBCGUI/CMakeFiles/ubcgui.dir/build
.PHONY : ubcgui/fast

#=============================================================================
# Target rules for targets named ubcsimplegeometry

# Build rule for target.
ubcsimplegeometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubcsimplegeometry
.PHONY : ubcsimplegeometry

# fast build rule for target.
ubcsimplegeometry/fast:
	$(MAKE) -f UBCSimpleGeometry/CMakeFiles/ubcsimplegeometry.dir/build.make UBCSimpleGeometry/CMakeFiles/ubcsimplegeometry.dir/build
.PHONY : ubcsimplegeometry/fast

#=============================================================================
# Target rules for targets named ubcutil

# Build rule for target.
ubcutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubcutil
.PHONY : ubcutil

# fast build rule for target.
ubcutil/fast:
	$(MAKE) -f UBCUtil/CMakeFiles/ubcutil.dir/build.make UBCUtil/CMakeFiles/ubcutil.dir/build
.PHONY : ubcutil/fast

#=============================================================================
# Target rules for targets named UBCViconSimpleGeometry

# Build rule for target.
UBCViconSimpleGeometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UBCViconSimpleGeometry
.PHONY : UBCViconSimpleGeometry

# fast build rule for target.
UBCViconSimpleGeometry/fast:
	$(MAKE) -f UBCViconSimpleGeometry/CMakeFiles/UBCViconSimpleGeometry.dir/build.make UBCViconSimpleGeometry/CMakeFiles/UBCViconSimpleGeometry.dir/build
.PHONY : UBCViconSimpleGeometry/fast

#=============================================================================
# Target rules for targets named EllipseFit

# Build rule for target.
EllipseFit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EllipseFit
.PHONY : EllipseFit

# fast build rule for target.
EllipseFit/fast:
	$(MAKE) -f EllipseFit/CMakeFiles/EllipseFit.dir/build.make EllipseFit/CMakeFiles/EllipseFit.dir/build
.PHONY : EllipseFit/fast

#=============================================================================
# Target rules for targets named ForwardKinematicsWAM

# Build rule for target.
ForwardKinematicsWAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ForwardKinematicsWAM
.PHONY : ForwardKinematicsWAM

# fast build rule for target.
ForwardKinematicsWAM/fast:
	$(MAKE) -f ForwardKinematicsWAM/CMakeFiles/ForwardKinematicsWAM.dir/build.make ForwardKinematicsWAM/CMakeFiles/ForwardKinematicsWAM.dir/build
.PHONY : ForwardKinematicsWAM/fast

#=============================================================================
# Target rules for targets named PathPlanning

# Build rule for target.
PathPlanning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PathPlanning
.PHONY : PathPlanning

# fast build rule for target.
PathPlanning/fast:
	$(MAKE) -f PathPlanning/CMakeFiles/PathPlanning.dir/build.make PathPlanning/CMakeFiles/PathPlanning.dir/build
.PHONY : PathPlanning/fast

#=============================================================================
# Target rules for targets named GetPos

# Build rule for target.
GetPos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GetPos
.PHONY : GetPos

# fast build rule for target.
GetPos/fast:
	$(MAKE) -f GetPos/CMakeFiles/GetPos.dir/build.make GetPos/CMakeFiles/GetPos.dir/build
.PHONY : GetPos/fast

# target to build an object file
uPredictor.o:
	$(MAKE) -f CMakeFiles/uPredictor.dir/build.make CMakeFiles/uPredictor.dir/uPredictor.o
.PHONY : uPredictor.o

# target to preprocess a source file
uPredictor.i:
	$(MAKE) -f CMakeFiles/uPredictor.dir/build.make CMakeFiles/uPredictor.dir/uPredictor.i
.PHONY : uPredictor.i

# target to generate assembly for a file
uPredictor.s:
	$(MAKE) -f CMakeFiles/uPredictor.dir/build.make CMakeFiles/uPredictor.dir/uPredictor.s
.PHONY : uPredictor.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... uPredictor"
	@echo "... ubccamera"
	@echo "... alglib"
	@echo "... ubckinect"
	@echo "... ubckinectgui"
	@echo "... ubcgui"
	@echo "... ubcsimplegeometry"
	@echo "... ubcutil"
	@echo "... UBCViconSimpleGeometry"
	@echo "... EllipseFit"
	@echo "... ForwardKinematicsWAM"
	@echo "... PathPlanning"
	@echo "... GetPos"
	@echo "... uPredictor.o"
	@echo "... uPredictor.i"
	@echo "... uPredictor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

